"""Shared Pydantic contracts. Import from here, not from the submodules."""

from pydantic import BaseModel

from strong_core.schemas.analysis import (
    CompetencyMatch,
    CompetencyRating,
    Gap,
    GapAnalysis,
    GapAssessment,
    PlannedSession,
    Rating,
    RequirementKind,
    RequirementMatch,
    RequirementRating,
    Strength,
)
from strong_core.schemas.base import Contract
from strong_core.schemas.enums import (
    COMPETENCIES_BY_TYPE,
    AuthProvider,
    Competency,
    Confidence,
    Difficulty,
    GapStatus,
    HireSignal,
    InterviewType,
    Level,
    Mode,
    OrgType,
    Phase,
    ProfileStatus,
    RoleFamily,
    SessionChannel,
    SessionStatus,
    Severity,
    Speaker,
    SubscriptionStatus,
    UsageComponent,
)
from strong_core.schemas.inputs import Education, JobPosting, Resume, ResumeRole
from strong_core.schemas.profile import (
    CaseStyle,
    CompanyProfile,
    LevelBar,
    LoopRound,
    LoopStructure,
    PersonaNotes,
    Principle,
    ProfileField,
    ProfileMeta,
    QuestionPattern,
    Source,
    ValuesFramework,
)
from strong_core.schemas.scoring import (
    CompetencyScore,
    ProgressSnapshot,
    QuestionScore,
    Scorecard,
    ValueScore,
)
from strong_core.schemas.session import (
    BriefDraft,
    BriefQuestion,
    InterviewerBrief,
    PersonaBrief,
    PhaseTime,
    SessionConfig,
    Turn,
)

# Models exported to schemas/<name>.schema.json by `python -m strong_core.export_schemas`.
EXPORTED_SCHEMAS: dict[str, type[BaseModel]] = {
    "job_posting": JobPosting,
    "resume": Resume,
    "company_profile": CompanyProfile,
    "gap_analysis": GapAnalysis,
    "gap_assessment": GapAssessment,
    "brief_draft": BriefDraft,
    "session_config": SessionConfig,
    "interviewer_brief": InterviewerBrief,
    "turn": Turn,
    "scorecard": Scorecard,
    "progress_snapshot": ProgressSnapshot,
}

__all__ = [
    "COMPETENCIES_BY_TYPE",
    "EXPORTED_SCHEMAS",
    "AuthProvider",
    "BriefDraft",
    "BriefQuestion",
    "CaseStyle",
    "CompanyProfile",
    "Competency",
    "CompetencyMatch",
    "CompetencyRating",
    "CompetencyScore",
    "Confidence",
    "Contract",
    "Difficulty",
    "Education",
    "Gap",
    "GapAnalysis",
    "GapAssessment",
    "GapStatus",
    "HireSignal",
    "InterviewType",
    "InterviewerBrief",
    "JobPosting",
    "Level",
    "LevelBar",
    "LoopRound",
    "LoopStructure",
    "Mode",
    "OrgType",
    "PersonaBrief",
    "PersonaNotes",
    "Phase",
    "PhaseTime",
    "PlannedSession",
    "Principle",
    "ProfileField",
    "ProfileMeta",
    "ProfileStatus",
    "ProgressSnapshot",
    "QuestionPattern",
    "QuestionScore",
    "Rating",
    "RequirementKind",
    "RequirementMatch",
    "RequirementRating",
    "Resume",
    "ResumeRole",
    "RoleFamily",
    "Scorecard",
    "SessionChannel",
    "SessionConfig",
    "SessionStatus",
    "Severity",
    "Source",
    "Speaker",
    "Strength",
    "SubscriptionStatus",
    "Turn",
    "UsageComponent",
    "ValueScore",
    "ValuesFramework",
]
