/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_auth_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Magic Link */
        post: operations["send_magic_link_auth_magic_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Magic Link Callback */
        get: operations["magic_link_callback_auth_magic_link_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["google_login_auth_google_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Login
         * @description Local only (APP_ENV=local). Signs in any email with no check.
         */
        post: operations["dev_login_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthProvider
         * @enum {string}
         */
        AuthProvider: "google" | "email" | "dev";
        /** AuthProviders */
        AuthProviders: {
            /** Google */
            google: boolean;
            /** Email */
            email: boolean;
            /** Dev */
            dev: boolean;
        };
        /** AuthState */
        AuthState: {
            /**
             * Status
             * @enum {string}
             */
            status: "signed_out" | "needs_signup" | "signed_in";
            /**
             * Email
             * @description Set for needs_signup and signed_in.
             */
            email?: string | null;
            user?: components["schemas"]["AuthUser"] | null;
        };
        /** AuthUser */
        AuthUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Email */
            email: string;
            auth_provider: components["schemas"]["AuthProvider"];
            /** Training Consent */
            training_consent: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BriefQuestion */
        BriefQuestion: {
            /**
             * Id
             * @description Stable id, used as Turn.question_ref.
             */
            id: string;
            /** Text */
            text: string;
            /** Competencies */
            competencies: components["schemas"]["Competency"][];
            /**
             * Priority
             * @description 1 is asked first.
             */
            priority: number;
            /** Probe Hints */
            probe_hints?: string[];
        };
        /**
         * CaseStyle
         * @description Relative emphasis, each from 0 to 1.
         */
        CaseStyle: {
            /** Product Sense */
            product_sense: number;
            /** Estimation */
            estimation: number;
            /** System Thinking */
            system_thinking: number;
            /**
             * Notes
             * @default null
             */
            notes: string | null;
        };
        /** CompanyProfile */
        CompanyProfile: {
            /** Company Name */
            company_name: string;
            /** Company Slug */
            company_slug: string;
            meta: components["schemas"]["ProfileMeta"];
            values_framework: components["schemas"]["ValuesFramework"];
            /** Loop Structure */
            loop_structure: components["schemas"]["LoopStructure"][];
            /** Question Patterns */
            question_patterns: components["schemas"]["QuestionPattern"][];
            /** Bar By Level */
            bar_by_level: components["schemas"]["LevelBar"][];
            persona: components["schemas"]["PersonaNotes"];
            /**
             * Scoring Weights
             * @description Relative weight of each competency in the hire signal. Missing means 1.0.
             */
            scoring_weights: {
                [key: string]: number;
            };
            case_style: components["schemas"]["CaseStyle"];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /**
             * Field Confidence
             * @description Confidence per field. Every ProfileField must be present.
             */
            field_confidence: {
                [key: string]: components["schemas"]["Confidence"];
            };
            /**
             * Low Confidence Notes
             * @description Fields or claims flagged for reviewer attention.
             */
            low_confidence_notes?: string[];
        };
        /**
         * Competency
         * @description Scored competencies from the spec, grouped by interview type in COMPETENCIES_BY_TYPE.
         * @enum {string}
         */
        Competency: "ownership" | "impact" | "collaboration" | "conflict_handling" | "learning_from_failure" | "communication" | "role_fit" | "depth_of_experience" | "judgment" | "motivation" | "team_fit" | "scope_at_level" | "technical_depth" | "accuracy" | "reasoning" | "trade_offs" | "clarity_of_explanation" | "problem_framing" | "structure" | "user_and_business_sense" | "estimation_logic" | "prioritization" | "recommendation";
        /** CompetencyMatch */
        CompetencyMatch: {
            competency: components["schemas"]["Competency"];
            /** Score */
            score: number;
            /**
             * Notes
             * @default null
             */
            notes: string | null;
        };
        /** CompetencyScore */
        CompetencyScore: {
            competency: components["schemas"]["Competency"];
            /** Score */
            score: number;
            /** Justification */
            justification: string;
            /**
             * Quotes
             * @description Transcript quotes backing the score.
             */
            quotes: string[];
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "low" | "medium" | "high";
        /** DevLoginRequest */
        DevLoginRequest: {
            /**
             * Email
             * @default dev@example.com
             */
            email: string;
        };
        /**
         * Difficulty
         * @description IV-4.
         * @enum {string}
         */
        Difficulty: "friendly" | "realistic" | "tough";
        /** Education */
        Education: {
            /** Institution */
            institution: string;
            /**
             * Degree
             * @default null
             */
            degree: string | null;
            /**
             * Field Of Study
             * @default null
             */
            field_of_study: string | null;
            /**
             * End
             * @default null
             */
            end: string | null;
        };
        /** Gap */
        Gap: {
            /** Summary */
            summary: string;
            severity: components["schemas"]["Severity"];
            /**
             * Related Requirement
             * @default null
             */
            related_requirement: string | null;
        };
        /** GapAnalysis */
        GapAnalysis: {
            /**
             * Match Score
             * @description GA-1.
             */
            match_score: number;
            /** Requirement Breakdown */
            requirement_breakdown?: components["schemas"]["RequirementMatch"][];
            /** Competency Breakdown */
            competency_breakdown?: components["schemas"]["CompetencyMatch"][];
            /** Strengths */
            strengths?: components["schemas"]["Strength"][];
            /** Gaps */
            gaps?: components["schemas"]["Gap"][];
            /** Probe Areas */
            probe_areas?: string[];
            /** Session Plan */
            session_plan: components["schemas"]["PlannedSession"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HireSignal
         * @description FB-1. Ordered from strongest to weakest.
         * @enum {string}
         */
        HireSignal: "Strong Hire" | "Hire" | "Lean Hire" | "Lean No Hire" | "No Hire";
        /**
         * InterviewType
         * @description The four v1 interview types (IV-2).
         * @enum {string}
         */
        InterviewType: "behavioral" | "hiring_manager" | "technical_qa" | "case";
        /**
         * InterviewerBrief
         * @description Built by the planner before each session. The live interviewer reads only this.
         */
        InterviewerBrief: {
            session: components["schemas"]["SessionConfig"];
            /**
             * Company Name
             * @description None in generic mode.
             * @default null
             */
            company_name: string | null;
            /** Generic Mode */
            generic_mode: boolean;
            /**
             * Profile Version
             * @default null
             */
            profile_version: number | null;
            /** Target Competencies */
            target_competencies: components["schemas"]["Competency"][];
            /** Questions */
            questions: components["schemas"]["BriefQuestion"][];
            /** Probe Areas */
            probe_areas?: string[];
            persona: components["schemas"]["PersonaBrief"];
            /**
             * Max Probes Per Question
             * @description IV-3.
             */
            max_probes_per_question: number;
            /**
             * Curveball
             * @description Tough difficulty only (IV-4).
             * @default null
             */
            curveball: string | null;
        };
        /**
         * JobPosting
         * @description Structured data extracted from a job posting. The user confirms or edits it (IN-2).
         */
        JobPosting: {
            /** Company Name */
            company_name: string;
            /** Title */
            title: string;
            /** @default other */
            role_family: components["schemas"]["RoleFamily"];
            /**
             * @description Normalized level, if it can be inferred.
             * @default null
             */
            level: components["schemas"]["Level"] | null;
            /**
             * Level Label
             * @description Level as written in the posting, for example 'L5' or 'Senior'.
             * @default null
             */
            level_label: string | null;
            /**
             * Team
             * @default null
             */
            team: string | null;
            /**
             * Location
             * @default null
             */
            location: string | null;
            /** Must Have Skills */
            must_have_skills?: string[];
            /** Nice To Have Skills */
            nice_to_have_skills?: string[];
            /** Responsibilities */
            responsibilities?: string[];
            /**
             * Source Url
             * @default null
             */
            source_url: string | null;
        };
        /**
         * Level
         * @description Normalized seniority (IV-6). Company-specific labels such as L5 or E5 map to these.
         * @enum {string}
         */
        Level: "new_grad" | "mid" | "senior" | "staff_principal";
        /** LevelBar */
        LevelBar: {
            /**
             * Level Name
             * @description Company label, for example 'L5' or 'E5'.
             */
            level_name: string;
            normalized_level: components["schemas"]["Level"];
            /** @default null */
            role_family: components["schemas"]["RoleFamily"] | null;
            /** Scope Expectation */
            scope_expectation: string;
        };
        /** LoopRound */
        LoopRound: {
            /** Name */
            name: string;
            /**
             * @description None for rounds v1 does not simulate, such as live coding.
             * @default null
             */
            interview_type: components["schemas"]["InterviewType"] | null;
            /**
             * Duration Min
             * @default null
             */
            duration_min: number | null;
            /**
             * Interviewer Role
             * @default null
             */
            interviewer_role: string | null;
            /**
             * Notes
             * @default null
             */
            notes: string | null;
        };
        /** LoopStructure */
        LoopStructure: {
            role_family: components["schemas"]["RoleFamily"];
            /**
             * Levels
             * @description Company level names covered.
             */
            levels?: string[];
            /** Rounds */
            rounds: components["schemas"]["LoopRound"][];
        };
        /** MagicLinkRequest */
        MagicLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** MagicLinkSent */
        MagicLinkSent: {
            /** Sent */
            sent: boolean;
            /**
             * Dev Link
             * @description Only when APP_ENV=local, so no email server is needed.
             */
            dev_link?: string | null;
        };
        /**
         * Mode
         * @description IV-8. Only Realistic sessions count toward progress trends (PR-1).
         * @enum {string}
         */
        Mode: "coach" | "realistic";
        /** PersonaBrief */
        PersonaBrief: {
            /** Tone */
            tone: string;
            /** Pushback Style */
            pushback_style: string;
            /** Closing Style */
            closing_style: string;
        };
        /** PersonaNotes */
        PersonaNotes: {
            /** Tone */
            tone: string;
            /** Pace */
            pace: string;
            /** Pushback Style */
            pushback_style: string;
            /** Closing Style */
            closing_style: string;
        };
        /**
         * Phase
         * @description Session state machine phases (IV-7). The session controller moves phases, not the LLM.
         * @enum {string}
         */
        Phase: "intro" | "small_talk" | "agenda" | "core" | "candidate_questions" | "wrap_up";
        /**
         * PlannedSession
         * @description One recommended practice session (GA-3).
         */
        PlannedSession: {
            /**
             * Priority
             * @description 1 is the first session to run.
             */
            priority: number;
            interview_type: components["schemas"]["InterviewType"];
            /** @default realistic */
            difficulty: components["schemas"]["Difficulty"];
            /** Focus Topics */
            focus_topics: string[];
            /** Reason */
            reason: string;
        };
        /** Principle */
        Principle: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Evidence Signals
             * @description What evidence of this principle sounds like in an answer.
             */
            evidence_signals: string[];
        };
        /**
         * ProfileField
         * @description Top-level profile fields that carry sources and a confidence level.
         * @enum {string}
         */
        ProfileField: "values_framework" | "loop_structure" | "question_patterns" | "bar_by_level" | "persona" | "scoring_weights" | "case_style";
        /** ProfileMeta */
        ProfileMeta: {
            /** Version */
            version: number;
            /** @default draft */
            status: components["schemas"]["ProfileStatus"];
            /**
             * Reviewed By
             * @default null
             */
            reviewed_by: string | null;
            /**
             * Researched At
             * @default null
             */
            researched_at: string | null;
            /**
             * Published At
             * @default null
             */
            published_at: string | null;
        };
        /**
         * ProfileStatus
         * @enum {string}
         */
        ProfileStatus: "draft" | "in_review" | "published" | "archived";
        /**
         * ProgressSnapshot
         * @description One competency score from one Realistic session, for trend charts (PR-1).
         */
        ProgressSnapshot: {
            /**
             * Job Target Id
             * Format: uuid
             */
            job_target_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            competency: components["schemas"]["Competency"];
            /** Score */
            score: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * QuestionPattern
         * @description A recurring theme, phrased as a pattern. Never a leaked or NDA-protected question.
         */
        QuestionPattern: {
            interview_type: components["schemas"]["InterviewType"];
            /** Theme */
            theme: string;
            /** Pattern */
            pattern: string;
            /** Competencies */
            competencies?: components["schemas"]["Competency"][];
        };
        /** QuestionScore */
        QuestionScore: {
            /** Question Ref */
            question_ref: string;
            /** Question Text */
            question_text: string;
            /** Scores */
            scores: components["schemas"]["CompetencyScore"][];
            /** Strengths */
            strengths?: string[];
            /** Misses */
            misses?: string[];
        };
        /**
         * RequirementKind
         * @enum {string}
         */
        RequirementKind: "must_have" | "nice_to_have";
        /** RequirementMatch */
        RequirementMatch: {
            /** Requirement */
            requirement: string;
            kind: components["schemas"]["RequirementKind"];
            /** Score */
            score: number;
            /**
             * Evidence
             * @description Resume text that supports the score.
             * @default null
             */
            evidence: string | null;
        };
        /**
         * Resume
         * @description A parsed resume (IN-3). Contact details are deliberately not part of the contract.
         */
        Resume: {
            /**
             * Summary
             * @default null
             */
            summary: string | null;
            /** Roles */
            roles?: components["schemas"]["ResumeRole"][];
            /** Skills */
            skills?: string[];
            /** Education */
            education?: components["schemas"]["Education"][];
            /** Certifications */
            certifications?: string[];
        };
        /** ResumeRole */
        ResumeRole: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /**
             * Start
             * @default null
             */
            start: string | null;
            /**
             * End
             * @description None means current role.
             * @default null
             */
            end: string | null;
            /** Achievements */
            achievements?: string[];
            /** Skills */
            skills?: string[];
        };
        /**
         * RoleFamily
         * @enum {string}
         */
        RoleFamily: "swe" | "data_ml" | "pm" | "design" | "tpm" | "other";
        /** Scorecard */
        Scorecard: {
            hire_signal: components["schemas"]["HireSignal"];
            /**
             * Rationale
             * @description 3 to 5 sentences, like a debrief summary.
             */
            rationale: string;
            /**
             * Competency Scores
             * @description Overall score per competency across the session.
             */
            competency_scores: components["schemas"]["CompetencyScore"][];
            /** Per Question */
            per_question?: components["schemas"]["QuestionScore"][];
            /**
             * Scorer Model
             * @description Gateway model alias, never a vendor id.
             */
            scorer_model: string;
            /**
             * Rubric Version
             * @description Prompt ref, for example 'scorer/rubric.v1'.
             */
            rubric_version: string;
        };
        /**
         * SessionConfig
         * @description What the candidate picks before a session (journey 2, step 1).
         */
        SessionConfig: {
            interview_type: components["schemas"]["InterviewType"];
            difficulty: components["schemas"]["Difficulty"];
            mode: components["schemas"]["Mode"];
            /**
             * Duration Min
             * @enum {integer}
             */
            duration_min: 30 | 45;
            level: components["schemas"]["Level"];
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "created" | "in_progress" | "interrupted" | "scoring" | "completed" | "failed";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high";
        /** SignupRequest */
        SignupRequest: {
            /**
             * Age Confirmed
             * @description The user confirmed they are 18 or older.
             */
            age_confirmed: boolean;
            /** Terms Accepted */
            terms_accepted: boolean;
            /**
             * Training Consent
             * @description AC-2: off unless the user opts in.
             * @default false
             */
            training_consent: boolean;
        };
        /** Source */
        Source: {
            /** Url */
            url: string;
            /**
             * Title
             * @default null
             */
            title: string | null;
            /**
             * Retrieved At
             * Format: date
             */
            retrieved_at: string;
            /**
             * Fields
             * @description Which profile fields this source supports.
             */
            fields: components["schemas"]["ProfileField"][];
        };
        /**
         * Speaker
         * @enum {string}
         */
        Speaker: "interviewer" | "candidate";
        /** Strength */
        Strength: {
            /** Summary */
            summary: string;
            /**
             * Evidence
             * @description Resume evidence (GA-2).
             */
            evidence: string;
        };
        /**
         * SubscriptionStatus
         * @description Mirrors the Stripe subscription statuses we act on.
         * @enum {string}
         */
        SubscriptionStatus: "trialing" | "active" | "past_due" | "canceled" | "incomplete";
        /**
         * Turn
         * @description One utterance in the transcript. Text only; audio is never stored.
         */
        Turn: {
            speaker: components["schemas"]["Speaker"];
            phase: components["schemas"]["Phase"];
            /** Text */
            text: string;
            /**
             * Start Ms
             * @description Offset from session start.
             */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /**
             * Question Ref
             * @description BriefQuestion.id, in CORE only.
             * @default null
             */
            question_ref: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValuesFramework */
        ValuesFramework: {
            /**
             * Name
             * @description For example 'Leadership Principles'.
             */
            name: string;
            /** Principles */
            principles: components["schemas"]["Principle"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    providers_auth_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProviders"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_magic_link_auth_magic_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicLinkSent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    magic_link_callback_auth_magic_link_callback_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_auth_google_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dev_login_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
